# Generated by Django 3.1.1 on 2020-11-18 20:11

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to=posts.models.upload_location, width_field='width')),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('publish', models.DateField(auto_now=True)),
            ],
        ),
    ]
