# Generated by Django 3.1.1 on 2021-06-07 20:10

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_slug'),
        ('posts', '0004_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location),
        ),
    ]
