# Generated by Django 3.1.1 on 2021-02-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='dislike',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='like',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
