# Generated by Django 3.1.1 on 2021-02-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20210228_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='dislike',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='like',
        ),
    ]
