# Generated by Django 3.1.1 on 2021-03-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
